/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://utjoesyvkfct3e6ckxz43olike.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x6v3wyqmgbd4xda3bocj3ptgnm",
    "aws_cognito_identity_pool_id": "us-east-2:3cf9fa86-68c7-4a2e-b1c4-5bd6b4e982bf",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lnEW7xAlk",
    "aws_user_pools_web_client_id": "6tkvuingignt3u8j6684n802ee",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
